# Create NumPy Array

In [1]:
import numpy as np

myList = [4, 6, 9, 10]
myArr1 = np.array(myList)
myArr1

array([ 4,  6,  9, 10])

In [2]:
myMatrix = [[1, 2, 3, 4], [5, 6, 7, 8]]
myArr2 = np.array(myMatrix)
myArr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
myArr3 = np.arange(0, 20)
myArr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
myArr4 = np.arange(0, 20, 2)
myArr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
myArr5 = np.linspace(0, 10, 6)
myArr5

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Generating Random Data

In [11]:
np.random.rand(5)

array([0.68110542, 0.3062619 , 0.94822567, 0.46148975, 0.64010927])

In [12]:
np.random.rand(6, 3)

array([[0.21483065, 0.00160636, 0.66084979],
       [0.98514529, 0.44122297, 0.58633875],
       [0.77686584, 0.84613429, 0.37903926],
       [0.47133089, 0.61262825, 0.10586822],
       [0.05118106, 0.73624832, 0.24697495],
       [0.78362389, 0.66027764, 0.94144246]])

In [13]:
np.random.randn(10)

array([ 0.9471881 , -0.82614225,  1.31691856,  1.08955286,  1.98349359,
        1.51967088,  0.91770897, -0.38520077,  0.58237569, -0.09533018])

In [14]:
np.random.randint(0, 10, 5)

array([6, 5, 2, 5, 4])

In [15]:
np.random.randint(0, 10, (3,3))

array([[2, 9, 8],
       [8, 3, 5],
       [1, 0, 3]])

# Restructuring NumPy Array

In [16]:
myArr = np.arange(0, 50)
print(myArr)

print("\n")

myArr = myArr.reshape(5, 10)
print(myArr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


# NumPy Indexing and Selection

In [17]:
myArr = np.arange(1, 20)
print(myArr)
print("\n")
print(myArr[2])
print("\n")
print(myArr[2:7])
print("\n")
print(myArr[:7])
print("\n")
print(myArr[7:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


3


[3 4 5 6 7]


[1 2 3 4 5 6 7]


[ 8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
myArr2d = np.arange(0, 20)
myArr2d = myArr2d.reshape(5,4)
print(myArr2d)
print("\n")
print(myArr2d[2, 3])
print("\n")
print(myArr2d[1:4, 2:4])
print("\n")
print(myArr2d[3:, :2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


11


[[ 6  7]
 [10 11]
 [14 15]]


[[12 13]
 [16 17]]


In [19]:
myArr = np.random.randint(0, 1000, 20 )
print(myArr)
print("\n")
print(myArr[myArr > 500])

[776 811 542 515  55 630 527 159 965 263  99 524 574 690 540 779 600 440
  14 774]


[776 811 542 515 630 527 965 524 574 690 540 779 600 774]


# NumPy Operations

In [21]:
myArr = np.arange(0, 20)
print(myArr)
print("\n")
print(myArr + 2)
print("\n")
print(myArr - 2)
print("\n")
print(myArr * 2)
print("\n")
print(myArr / 2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]


[-2 -1  0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [22]:
print(np.sqrt(myArr))
print("\n")
print(np.sin(myArr))
print("\n")
print(np.cos(myArr))
print("\n")
print(np.log(myArr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563
 4.24264069 4.35889894]


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749
 -0.75098725  0.14987721]


[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527
 2.48490665 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334
 2.89037176 2.94443898]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log
  import sys


# NumPy Statistics

In [23]:
myArr = np.random.randint(0, 1000, 20 )
print(myArr)
print("\n")
print(myArr.max())
print(myArr.argmax())
print("\n")
print(myArr.min())
print(myArr.argmin())

[595 708 869 918 246 393 176 887 293 494 612 162 855 617 342 435 134 307
 235  36]


918
3


36
19


In [24]:
print(myArr.sum())
print("\n")
print(myArr.mean())
print("\n")
print(myArr.var())
print("\n")
print(myArr.std())

9314


465.7


73282.81


270.7079791952945


In [25]:
myArr2d = np.arange(0, 20)
myArr2d = myArr2d.reshape(5,4)
print(myArr2d)
print("\n")
print(myArr2d.sum(axis=0))
print(myArr2d.sum(axis=1))
print("\n")
print(myArr2d.mean(axis=0))
print(myArr2d.mean(axis=1))
print("\n")
print(myArr2d.var(axis=0))
print(myArr2d.var(axis=1))
print("\n")
print(myArr2d.std(axis=0))
print(myArr2d.std(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


[40 45 50 55]
[ 6 22 38 54 70]


[ 8.  9. 10. 11.]
[ 1.5  5.5  9.5 13.5 17.5]


[32. 32. 32. 32.]
[1.25 1.25 1.25 1.25 1.25]


[5.65685425 5.65685425 5.65685425 5.65685425]
[1.11803399 1.11803399 1.11803399 1.11803399 1.11803399]
